
[colors]
draw_bold_text_with_bright_colors = true
#
# [colors.bright]
# black = "#27272a"
# red = "#f5a191"
# green = "#90b99f"
# yellow = "#f0c5a9"
# blue = "#aca1cf"
# magenta = "#aca1cf"
# cyan = "#e29eca"
# white = "#ea83a5"
#
# [colors.cursor]
# cursor = "#c1c0d4"
# text = "#353539"
#
# [colors.normal]
# black = "#000000"
# red = "#ffae9f"
# green = "#9dc6ac"
# yellow = "#f0c5a9"
# blue = "#b9aeda"
# magenta = "#ecaad6"
# cyan = "#f591b2"
# white = "#cac9dd"
#
# [colors.primary]
# background = "#1a1a19"
# foreground = "#c9c7cd"

[env]
TERM = "xterm-256color"

[scrolling]
history = 20000
multiplier = 3

[terminal.shell]
program = "tmux"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
import = [
	"~/.config/alacritty/font.toml",
	"~/.config/alacritty/rasmus.toml"
]

[terminal]
