[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#585146"
red = "#d3643b"
green = "#a7da1e"
yellow = "#f4d370"
blue = "#94c7b6"
magenta = "#e61f44"
cyan = "#edebe6"
white = "#edebe6"

[colors.cursor]
cursor = "#d1d1d1"
text = "#1a1a19"

[colors.normal]
black = "#000000"
red = "#d3643b"
green = "#a7da1e"
yellow = "#f4d370"
blue = "#94c7b6"
magenta = "#e61f44"
cyan = "#edebe6"
white = "#edebe6"

[colors.primary]
background = "#0c0b0a"
foreground = "#c5c9c5"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 3

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
